DROP DATABASE CMSDB
CREATE DATABASE CMSDB

USE CMSDB



CREATE TABLE Person(
	UID INT PRIMARY KEY,
	Username VARCHAR(50),
	Password VARCHAR(50),
	Website  VARCHAR(200),
	Affiliation VARCHAR(50),
	FirstName VARCHAR(50),
	LastNAme VARCHAR(50),
	PhoneNumber VARCHAR(12),
	Email VARCHAR(50),
	AcademicRank VARCHAR(20)
	);

CREATE TABLE Chair(
	CID INT PRIMARY KEY,
	UID INT FOREIGN KEY REFERENCES Person(UID),
	);

CREATE TABLE PC(
	PCID INT PRIMARY KEY,
	UID INT FOREIGN KEY REFERENCES Person(UID),
	);

CREATE TABLE Author(
	AID INT PRIMARY KEY,
	UID INT FOREIGN KEY REFERENCES Person(UID),
	);

CREATE TABLE Room(
	RID INT PRIMARY KEY, 
	Capacity INT
	);

CREATE TABLE Session(
	SID INT PRIMARY KEY,
	Supervisor INT FOREIGN KEY REFERENCES PC(PCID),
	Time DATETIME,
	RID INT FOREIGN KEY REFERENCES Room(RID)
	);

CREATE TABLE Paper(
	PID INT PRIMARY KEY,
	AID INT FOREIGN KEY REFERENCES Author(AID),
	Topic VARCHAR(50),
	Accepted CHAR(10),
	Session INT FOREIGN KEY REFERENCES Session(SID),
	AbstractURL VARCHAR(50),
	ContentURL VARCHAR(50),
	PresentationURL VARCHAR(50)
	);

CREATE TABLE Keyword(
	KID INT PRIMARY KEY,
	Name VARCHAR(50) 
	);

CREATE TABLE PaperSubjects( 
	PID INT REFERENCES Paper(PID),
	KID INT REFERENCES Keyword(KID),
	PRIMARY KEY (PID,KID)
	);

CREATE TABLE Bidding(
	PCID INT FOREIGN KEY REFERENCES PC(PCID),
	PID INT FOREIGN KEY REFERENCES Paper(PID),
	PRIMARY KEY(PCID, PID),
	);

CREATE TABLE Assignment(
	PCID INT FOREIGN KEY REFERENCES PC(PCID),
	PID INT FOREIGN KEY REFERENCES Paper(PID),
	CID INT FOREIGN KEY REFERENCES Chair(CID),
	PRIMARY KEY(PCID, PID),
	Qualifier INT
	);

CREATE TABLE Ticket(
	TID INT PRIMARY KEY,
	SID INT FOREIGN KEY REFERENCES Session(SID),
	PRICE DECIMAL(10,2),
	SeatNo INT,
	DatePurchased DATETIME,
	Name VARCHAR(50)
	);
